---
# SPDX-License-Identifier: Apache-2.0
# Always passed via --extra-vars by template.pkr.hcl. No real default — an
# empty string fails loudly (a malformed S3 URL) rather than silently
# baking an agent for the wrong region.
aws_region: ""
