#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Unix counterpart of initialize.cmd — see devcontainer.json's
# initializeCommand comment. Runs on the host before the container starts,
# to ensure the mount sources below exist (plain Linux Docker Engine fails
# the mount outright if they don't; Docker Desktop usually auto-creates them).
set -eu
mkdir -p ~/.ssh ~/.kube-compute ~/.aws
